spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./todoAppDB'
    driverClassName: org.h2.Driver
  jpa.hibernate:
    ddl-auto: validate

  management:
    endpoints:
      web:
        exposure:
          include: '*'